name = "deployer"
main = "src/index.js"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-08-23"

# The necessary secrets are:
# - DEPLOY_URLS
# - API_KEYS
#
# Add with wrangler cli / in dashboard