name = "deployer"
main = "index.js"
type = "webpack"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-08-23"

# The necessary secrets are:
# - DEPLOY_URLS
# - API_KEYS
#
# Add with wrangler cli / in dashboard

[vars]
API_KEYS = "1234,4567"
DEPLOY_URLS = '{"test":"https://httpbin.org/post"}'