name = "deployer"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-08-23"

# The necessary secrets are:
# - DEPLOY_URLS
# - API_KEYS
#
# Add with wrangler cli / in dashboard